# Application Details
spring.application.name=PlayStore
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/PlayStore
spring.datasource.username=postgres
spring.datasource.password=Ramesh@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Logging File
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.src=INFO
logging.file.name=logs/playstore-app.log